In [88]:
import numpy as np
import random

In [89]:
n = 100

In [90]:
x = [random.random() for k in range(n)]
y = [random.random() for k in range(n)]

In [91]:
xa = np.array(x)
ya = np.array(y)

In [92]:
xa[:1] - ya[:1]

array([0.06972621])

In [93]:
xa[:1, np.newaxis] - ya[:1]

array([[0.06972621]])

In [94]:
xa[:2] - ya[:2]

array([ 0.06972621, -0.3534016 ])

In [95]:
xa[:2, np.newaxis] - ya[:2]

array([[ 0.06972621,  0.14681247],
       [-0.43048786, -0.3534016 ]])

In [96]:
xa[:3] - ya[:3]

array([ 0.06972621, -0.3534016 , -0.30065422])

In [97]:
xa[:3, np.newaxis] - ya[:3]

array([[ 0.06972621,  0.14681247,  0.66166319],
       [-0.43048786, -0.3534016 ,  0.16144912],
       [-0.8925912 , -0.81550494, -0.30065422]])

In [98]:
xa[:3, np.newaxis] - ya[:3, np.newaxis]

array([[ 0.06972621],
       [-0.3534016 ],
       [-0.30065422]])

In [99]:
[abs(x[i] - y[j]) for i in range(3) for j in range(3)]

[0.06972620743191227,
 0.146812473430616,
 0.661663194040812,
 0.4304878635590299,
 0.3534015975603262,
 0.1614491230498698,
 0.892591202324653,
 0.8155049363259493,
 0.30065421571575335]